# Generated by Django 4.2.2 on 2026-03-29 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_testimonial_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
    ]
