# Generated by Django 4.2.2 on 2026-03-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_subject_grade_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
