# Generated by Django 4.2.2 on 2026-03-31 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_teacher_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Description',
            new_name='description',
        ),
    ]
